package mapper;

import com.jn.bean.JnshuFeature;

import java.util.List;

public interface JnshuFeatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jnshu_feature
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jnshu_feature
     *
     * @mbggenerated
     */
    int insert(JnshuFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jnshu_feature
     *
     * @mbggenerated
     */
    int insertSelective(JnshuFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jnshu_feature
     *
     * @mbggenerated
     */
    JnshuFeature selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jnshu_feature
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JnshuFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jnshu_feature
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JnshuFeature record);

    List<JnshuFeature> selectAll();
}