package mapper;

import com.jn.bean.JnshuStuShow;

public interface JnshuStuShowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jnshu_stuShow
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jnshu_stuShow
     *
     * @mbggenerated
     */
    int insert(JnshuStuShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jnshu_stuShow
     *
     * @mbggenerated
     */
    int insertSelective(JnshuStuShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jnshu_stuShow
     *
     * @mbggenerated
     */
    JnshuStuShow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jnshu_stuShow
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JnshuStuShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jnshu_stuShow
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JnshuStuShow record);
}