package mapper;

import com.jn.bean.PersistentLogins;
import org.apache.ibatis.annotations.Param;

public interface PersistentLoginsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated
     */
    int insert(PersistentLogins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated
     */
    int insertSelective(PersistentLogins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated
     */
    PersistentLogins selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PersistentLogins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PersistentLogins record);

    /**
     * 通过用户名和UUID值查询自动登录记录
     *
     * @param username
     *            用户名
     * @param series
     *            UUID值
     */
    PersistentLogins selectByUsernameAndSeries(@Param("username") String username, @Param("series") String series);

    /**
     * 通过用户名查询自动登录记录
     *
     * @param username
     *            用户名
     */
    PersistentLogins selectByUsername(@Param("username") String username);
}