package com.jn.bean;

import java.io.Serializable;

public class JnshuCareerPath implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jnshu_careerPath.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jnshu_careerPath.career_title
     *
     * @mbggenerated
     */
    private String careerTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jnshu_careerPath
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jnshu_careerPath.id
     *
     * @return the value of jnshu_careerPath.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jnshu_careerPath.id
     *
     * @param id the value for jnshu_careerPath.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jnshu_careerPath.career_title
     *
     * @return the value of jnshu_careerPath.career_title
     *
     * @mbggenerated
     */
    public String getCareerTitle() {
        return careerTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jnshu_careerPath.career_title
     *
     * @param careerTitle the value for jnshu_careerPath.career_title
     *
     * @mbggenerated
     */
    public void setCareerTitle(String careerTitle) {
        this.careerTitle = careerTitle == null ? null : careerTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jnshu_careerPath
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        JnshuCareerPath other = (JnshuCareerPath) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCareerTitle() == null ? other.getCareerTitle() == null : this.getCareerTitle().equals(other.getCareerTitle()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jnshu_careerPath
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCareerTitle() == null) ? 0 : getCareerTitle().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jnshu_careerPath
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", careerTitle=").append(careerTitle);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}