package com.jn.bean;

import java.io.Serializable;

public class Student implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_name
     *
     * @mbggenerated
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.qq
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.course_type_id
     *
     * @mbggenerated
     */
    private Long courseTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.school
     *
     * @mbggenerated
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.online_id
     *
     * @mbggenerated
     */
    private String onlineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.online_class_id
     *
     * @mbggenerated
     */
    private String onlineClassId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.will
     *
     * @mbggenerated
     */
    private String will;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.create_at
     *
     * @mbggenerated
     */
    private Long createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.update_at
     *
     * @mbggenerated
     */
    private Long updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.daily_link
     *
     * @mbggenerated
     */
    private String dailyLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.referer
     *
     * @mbggenerated
     */
    private String referer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.auditor
     *
     * @mbggenerated
     */
    private String auditor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.from_where
     *
     * @mbggenerated
     */
    private String fromWhere;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.avatar
     *
     * @mbggenerated
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.enroll_time
     *
     * @mbggenerated
     */
    private String enrollTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.ID
     *
     * @return the value of student.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.ID
     *
     * @param id the value for student.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_name
     *
     * @return the value of student.stu_name
     *
     * @mbggenerated
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_name
     *
     * @param stuName the value for student.stu_name
     *
     * @mbggenerated
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.qq
     *
     * @return the value of student.qq
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.qq
     *
     * @param qq the value for student.qq
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.course_type_id
     *
     * @return the value of student.course_type_id
     *
     * @mbggenerated
     */
    public Long getCourseTypeId() {
        return courseTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.course_type_id
     *
     * @param courseTypeId the value for student.course_type_id
     *
     * @mbggenerated
     */
    public void setCourseTypeId(Long courseTypeId) {
        this.courseTypeId = courseTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.school
     *
     * @return the value of student.school
     *
     * @mbggenerated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.school
     *
     * @param school the value for student.school
     *
     * @mbggenerated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.online_id
     *
     * @return the value of student.online_id
     *
     * @mbggenerated
     */
    public String getOnlineId() {
        return onlineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.online_id
     *
     * @param onlineId the value for student.online_id
     *
     * @mbggenerated
     */
    public void setOnlineId(String onlineId) {
        this.onlineId = onlineId == null ? null : onlineId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.online_class_id
     *
     * @return the value of student.online_class_id
     *
     * @mbggenerated
     */
    public String getOnlineClassId() {
        return onlineClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.online_class_id
     *
     * @param onlineClassId the value for student.online_class_id
     *
     * @mbggenerated
     */
    public void setOnlineClassId(String onlineClassId) {
        this.onlineClassId = onlineClassId == null ? null : onlineClassId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.will
     *
     * @return the value of student.will
     *
     * @mbggenerated
     */
    public String getWill() {
        return will;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.will
     *
     * @param will the value for student.will
     *
     * @mbggenerated
     */
    public void setWill(String will) {
        this.will = will == null ? null : will.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.create_at
     *
     * @return the value of student.create_at
     *
     * @mbggenerated
     */
    public Long getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.create_at
     *
     * @param createAt the value for student.create_at
     *
     * @mbggenerated
     */
    public void setCreateAt(Long createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.update_at
     *
     * @return the value of student.update_at
     *
     * @mbggenerated
     */
    public Long getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.update_at
     *
     * @param updateAt the value for student.update_at
     *
     * @mbggenerated
     */
    public void setUpdateAt(Long updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.daily_link
     *
     * @return the value of student.daily_link
     *
     * @mbggenerated
     */
    public String getDailyLink() {
        return dailyLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.daily_link
     *
     * @param dailyLink the value for student.daily_link
     *
     * @mbggenerated
     */
    public void setDailyLink(String dailyLink) {
        this.dailyLink = dailyLink == null ? null : dailyLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.referer
     *
     * @return the value of student.referer
     *
     * @mbggenerated
     */
    public String getReferer() {
        return referer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.referer
     *
     * @param referer the value for student.referer
     *
     * @mbggenerated
     */
    public void setReferer(String referer) {
        this.referer = referer == null ? null : referer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.auditor
     *
     * @return the value of student.auditor
     *
     * @mbggenerated
     */
    public String getAuditor() {
        return auditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.auditor
     *
     * @param auditor the value for student.auditor
     *
     * @mbggenerated
     */
    public void setAuditor(String auditor) {
        this.auditor = auditor == null ? null : auditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.from_where
     *
     * @return the value of student.from_where
     *
     * @mbggenerated
     */
    public String getFromWhere() {
        return fromWhere;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.from_where
     *
     * @param fromWhere the value for student.from_where
     *
     * @mbggenerated
     */
    public void setFromWhere(String fromWhere) {
        this.fromWhere = fromWhere == null ? null : fromWhere.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.mobile
     *
     * @return the value of student.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.mobile
     *
     * @param mobile the value for student.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.avatar
     *
     * @return the value of student.avatar
     *
     * @mbggenerated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.avatar
     *
     * @param avatar the value for student.avatar
     *
     * @mbggenerated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.email
     *
     * @return the value of student.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.email
     *
     * @param email the value for student.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.enroll_time
     *
     * @return the value of student.enroll_time
     *
     * @mbggenerated
     */
    public String getEnrollTime() {
        return enrollTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.enroll_time
     *
     * @param enrollTime the value for student.enroll_time
     *
     * @mbggenerated
     */
    public void setEnrollTime(String enrollTime) {
        this.enrollTime = enrollTime == null ? null : enrollTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Student other = (Student) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getStuName() == null ? other.getStuName() == null : this.getStuName().equals(other.getStuName()))
            && (this.getQq() == null ? other.getQq() == null : this.getQq().equals(other.getQq()))
            && (this.getCourseTypeId() == null ? other.getCourseTypeId() == null : this.getCourseTypeId().equals(other.getCourseTypeId()))
            && (this.getSchool() == null ? other.getSchool() == null : this.getSchool().equals(other.getSchool()))
            && (this.getOnlineId() == null ? other.getOnlineId() == null : this.getOnlineId().equals(other.getOnlineId()))
            && (this.getOnlineClassId() == null ? other.getOnlineClassId() == null : this.getOnlineClassId().equals(other.getOnlineClassId()))
            && (this.getWill() == null ? other.getWill() == null : this.getWill().equals(other.getWill()))
            && (this.getCreateAt() == null ? other.getCreateAt() == null : this.getCreateAt().equals(other.getCreateAt()))
            && (this.getUpdateAt() == null ? other.getUpdateAt() == null : this.getUpdateAt().equals(other.getUpdateAt()))
            && (this.getDailyLink() == null ? other.getDailyLink() == null : this.getDailyLink().equals(other.getDailyLink()))
            && (this.getReferer() == null ? other.getReferer() == null : this.getReferer().equals(other.getReferer()))
            && (this.getAuditor() == null ? other.getAuditor() == null : this.getAuditor().equals(other.getAuditor()))
            && (this.getFromWhere() == null ? other.getFromWhere() == null : this.getFromWhere().equals(other.getFromWhere()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getAvatar() == null ? other.getAvatar() == null : this.getAvatar().equals(other.getAvatar()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getEnrollTime() == null ? other.getEnrollTime() == null : this.getEnrollTime().equals(other.getEnrollTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getStuName() == null) ? 0 : getStuName().hashCode());
        result = prime * result + ((getQq() == null) ? 0 : getQq().hashCode());
        result = prime * result + ((getCourseTypeId() == null) ? 0 : getCourseTypeId().hashCode());
        result = prime * result + ((getSchool() == null) ? 0 : getSchool().hashCode());
        result = prime * result + ((getOnlineId() == null) ? 0 : getOnlineId().hashCode());
        result = prime * result + ((getOnlineClassId() == null) ? 0 : getOnlineClassId().hashCode());
        result = prime * result + ((getWill() == null) ? 0 : getWill().hashCode());
        result = prime * result + ((getCreateAt() == null) ? 0 : getCreateAt().hashCode());
        result = prime * result + ((getUpdateAt() == null) ? 0 : getUpdateAt().hashCode());
        result = prime * result + ((getDailyLink() == null) ? 0 : getDailyLink().hashCode());
        result = prime * result + ((getReferer() == null) ? 0 : getReferer().hashCode());
        result = prime * result + ((getAuditor() == null) ? 0 : getAuditor().hashCode());
        result = prime * result + ((getFromWhere() == null) ? 0 : getFromWhere().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getAvatar() == null) ? 0 : getAvatar().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getEnrollTime() == null) ? 0 : getEnrollTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", stuName=").append(stuName);
        sb.append(", qq=").append(qq);
        sb.append(", courseTypeId=").append(courseTypeId);
        sb.append(", school=").append(school);
        sb.append(", onlineId=").append(onlineId);
        sb.append(", onlineClassId=").append(onlineClassId);
        sb.append(", will=").append(will);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", dailyLink=").append(dailyLink);
        sb.append(", referer=").append(referer);
        sb.append(", auditor=").append(auditor);
        sb.append(", fromWhere=").append(fromWhere);
        sb.append(", mobile=").append(mobile);
        sb.append(", avatar=").append(avatar);
        sb.append(", email=").append(email);
        sb.append(", enrollTime=").append(enrollTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}